/* Pure port of MealPrep's C# NutritionCalcService (Services/NutritionCalcService.cs).
   No imports, no DB — callers pass already-loaded rows. Nutrition rows use the
   snake_case column names of the Supabase schema (energy_kcal, gm_wt_1, ...).
   Verified against golden vectors generated by the C# implementation. */

export const Status = {
  Counted: 'Counted',
  CountedApprox: 'CountedApprox',
  Negligible: 'Negligible',
  NoNutritionLink: 'NoNutritionLink',
  NoConversion: 'NoConversion',
};

const MASS_UNITS = { g: 1, kg: 1000, oz: 28.3495, lb: 453.592 };

const VOLUME_UNITS_ML = {
  'tsp': 4.92892, 'tbsp': 14.7868, 'fl oz': 29.5735, 'cup': 236.588,
  'pt': 473.176, 'qt': 946.353, 'gal': 3785.41, 'ml': 1, 'l': 1000,
};

const NEGLIGIBLE_UNITS = new Set(['pinch', 'dash', 'to taste']);

const VOLUME_KEYWORDS_ML = {
  'tsp': 4.92892, 'teaspoon': 4.92892,
  'tbsp': 14.7868, 'tablespoon': 14.7868,
  'fl oz': 29.5735,
  'cup': 236.588,
  'pt': 473.176, 'pint': 473.176,
  'qt': 946.353, 'quart': 946.353,
  'gal': 3785.41, 'gallon': 3785.41,
  'ml': 1, 'milliliter': 1,
  'l': 1000, 'liter': 1000, 'litre': 1000,
};

const COUNT_UNIT_KEYWORDS = {
  'whole': ['whole', 'medium', 'each', 'fruit', 'egg', 'large', 'small', 'potato', 'onion', 'pepper', 'banana', 'apple', 'muffin', 'tortilla', 'patty', 'link'],
  'slice': ['slice'],
  'clove': ['clove'],
  'piece': ['piece', 'each', 'whole', 'medium'],
  'can': ['can'],
  'bunch': ['bunch'],
  'sprig': ['sprig'],
  'head': ['head'],
  'stalk': ['stalk'],
};

const lower = s => (s ?? '').trim().toLowerCase();

/* "1 cup, diced" -> {count:1, keyword:'cup'}; ".5 cup" -> {count:0.5,...};
   mixed fractions "1 1/2 cup"; "fl oz" two-token merge; de-pluralize. */
export function parseGmWtDesc(desc){
  if (!desc || !desc.trim()) return null;
  const head = desc.split(',')[0].trim();
  if (!head) return null;
  const tokens = head.split(/\s+/).filter(Boolean);
  let count = 1, i = 0;
  const num = parseNumber(tokens[i]);
  if (num !== null){
    count = num;
    i++;
    if (i < tokens.length && tokens[i].includes('/')){
      const frac = parseNumber(tokens[i]);
      if (frac !== null){ count += frac; i++; }
    }
  }
  if (i >= tokens.length) return null;
  let keyword = tokens[i].toLowerCase().replace(/^[.()]+|[.()]+$/g, '');
  if (keyword === 'fl' && i + 1 < tokens.length && tokens[i + 1].toLowerCase().startsWith('oz'))
    keyword = 'fl oz';
  if (keyword.length > 1 && keyword.endsWith('s')) keyword = keyword.slice(0, -1);
  if (!keyword || count <= 0) return null;
  return { count, keyword };
}

function parseNumber(token){
  if (token === undefined) return null;
  if (token.includes('/')){
    const parts = token.split('/');
    if (parts.length !== 2) return null;
    const n = Number(parts[0]), d = Number(parts[1]);
    if (!isFinite(n) || !isFinite(d) || d === 0 || parts[0] === '' || parts[1] === '') return null;
    return n / d;
  }
  const v = Number(token);
  return token !== '' && isFinite(v) ? v : null;
}

function gmWtPairs(n){
  const pairs = [];
  if (n.gm_wt_1 != null && n.gm_wt_1 > 0 && n.gm_wt_desc1 && n.gm_wt_desc1.trim())
    pairs.push({ gmWt: n.gm_wt_1, desc: n.gm_wt_desc1 });
  if (n.gm_wt_2 != null && n.gm_wt_2 > 0 && n.gm_wt_desc2 && n.gm_wt_desc2.trim())
    pairs.push({ gmWt: n.gm_wt_2, desc: n.gm_wt_desc2 });
  return pairs;
}

function deriveDensityGPerMl(n){
  for (const { gmWt, desc } of gmWtPairs(n)){
    const parsed = parseGmWtDesc(desc);
    if (!parsed) continue;
    const ml = VOLUME_KEYWORDS_ML[parsed.keyword];
    if (ml > 0) return gmWt / (parsed.count * ml);
  }
  return null;
}

export function tryConvertToGrams(quantity, unit, n){
  unit = (unit ?? '').trim();
  const unitLc = unit.toLowerCase();

  if (NEGLIGIBLE_UNITS.has(unitLc)) return 0;

  if (Object.prototype.hasOwnProperty.call(MASS_UNITS, unitLc))
    return quantity * MASS_UNITS[unitLc];

  if (Object.prototype.hasOwnProperty.call(VOLUME_UNITS_ML, unitLc)){
    const density = deriveDensityGPerMl(n);
    return density !== null ? quantity * VOLUME_UNITS_ML[unitLc] * density : null;
  }

  const keywords = COUNT_UNIT_KEYWORDS[unitLc] || null;
  for (const { gmWt, desc } of gmWtPairs(n)){
    const parsed = parseGmWtDesc(desc);
    if (!parsed) continue;
    if (keywords && keywords.includes(parsed.keyword))
      return quantity * (gmWt / parsed.count);
  }

  if (n.gm_wt_1 != null && n.gm_wt_1 > 0)
    return quantity * n.gm_wt_1;

  return null;
}

export function isApproxConversion(unit, n){
  unit = (unit ?? '').trim();
  const unitLc = unit.toLowerCase();
  if (NEGLIGIBLE_UNITS.has(unitLc)
    || Object.prototype.hasOwnProperty.call(MASS_UNITS, unitLc)
    || Object.prototype.hasOwnProperty.call(VOLUME_UNITS_ML, unitLc)) return false;
  const keywords = COUNT_UNIT_KEYWORDS[unitLc] || null;
  for (const { desc } of gmWtPairs(n)){
    const parsed = parseGmWtDesc(desc);
    if (!parsed) continue;
    if (keywords && keywords.includes(parsed.keyword)) return false;
  }
  return n.gm_wt_1 != null && n.gm_wt_1 > 0;
}

/* Half-even rounding to 1 decimal (C# Math.Round(decimal, 1) banker's rounding). */
export function round1(x){
  const scaled = x * 10;
  const floor = Math.floor(scaled);
  const diff = scaled - floor;
  const eps = 1e-9;
  let r;
  if (diff > 0.5 + eps) r = floor + 1;
  else if (diff < 0.5 - eps) r = floor;
  else r = (floor % 2 === 0) ? floor : floor + 1;
  return r / 10;
}

/* items: [{ ingredient: {id, name, unit, nutrition: {…snake_case} | null}, quantity }] */
export function compute(items){
  const result = {
    calories: 0, proteinG: 0, fiberG: 0, ironMg: 0,
    items: [], hasApprox: false, uncountedNote: null,
    get hasUncounted(){ return this.items.some(i => i.status === Status.NoNutritionLink || i.status === Status.NoConversion); },
  };
  for (const { ingredient: ing, quantity: qty } of items){
    const item = {
      ingredientId: ing.id, name: ing.name, quantity: qty, unit: ing.unit,
      status: null, grams: null, calories: 0, proteinG: 0, fiberG: 0, ironMg: 0,
    };
    const n = ing.nutrition;
    if (!n){
      item.status = Status.NoNutritionLink;
    } else {
      const grams = tryConvertToGrams(qty, ing.unit, n);
      if (grams === null){
        item.status = Status.NoConversion;
      } else if (grams === 0 && NEGLIGIBLE_UNITS.has(lower(ing.unit))){
        item.status = Status.Negligible;
        item.grams = 0;
      } else {
        item.status = isApproxConversion(ing.unit ?? '', n) ? Status.CountedApprox : Status.Counted;
        item.grams = grams;
        const factor = grams / 100;
        item.calories = factor * (n.energy_kcal ?? 0);
        item.proteinG = factor * (n.protein_g ?? 0);
        item.fiberG = factor * (n.fiber_td_g ?? 0);
        item.ironMg = factor * (n.iron_mg ?? 0);
        result.calories += item.calories;
        result.proteinG += item.proteinG;
        result.fiberG += item.fiberG;
        result.ironMg += item.ironMg;
      }
    }
    if (item.status === Status.CountedApprox) result.hasApprox = true;
    result.items.push(item);
  }
  result.calories = round1(result.calories);
  result.proteinG = round1(result.proteinG);
  result.fiberG = round1(result.fiberG);
  result.ironMg = round1(result.ironMg);
  const uncounted = result.items.filter(i => i.status === Status.NoNutritionLink || i.status === Status.NoConversion);
  if (uncounted.length)
    result.uncountedNote = 'Not counted: ' + uncounted.map(u => u.name).join(', ');
  return result;
}

/* meal: {servings, recipe: {servings, ingredients:[{ingredient, quantity}]} | null,
          ingredients: [{ingredient, quantity}]} — rows already joined by caller */
export function computeForMeal(meal){
  if (meal.recipe && meal.recipe.ingredients && meal.recipe.ingredients.length){
    const recipeServings = meal.recipe.servings > 0 ? meal.recipe.servings : 1;
    const mealServings = meal.servings > 0 ? meal.servings : 1;
    const scale = mealServings / recipeServings;
    return compute(meal.recipe.ingredients.map(ri => ({ ingredient: ri.ingredient, quantity: ri.quantity * scale })));
  }
  return compute((meal.ingredients || []).map(mi => ({ ingredient: mi.ingredient, quantity: mi.quantity })));
}

export function computeForRecipe(recipe, servingsEaten){
  const recipeServings = recipe.servings > 0 ? recipe.servings : 1;
  const scale = servingsEaten / recipeServings;
  return compute((recipe.ingredients || []).map(ri => ({ ingredient: ri.ingredient, quantity: ri.quantity * scale })));
}
