"""Generate Supabase migration SQL from the MealPrep SQLite database.

Usage:  python tools/generate_migration.py [db_path] [out_dir]
Defaults: db_path = F:/Apps/MealPrepWeb/data/mealprep.db, out_dir = migration-out/

Output files are meant to be pasted into the Supabase SQL editor IN ORDER.
The out dir is gitignored: it contains personal data and must never be
committed to this public repo.
"""
import sqlite3
import sys
import os

DB = sys.argv[1] if len(sys.argv) > 1 else r"F:/Apps/MealPrepWeb/data/mealprep.db"
OUT = sys.argv[2] if len(sys.argv) > 2 else os.path.join(os.path.dirname(__file__), "..", "migration-out")
os.makedirs(OUT, exist_ok=True)

NUTRITION_COLS = [
    # (sqlite_name, pg_name, kind)  kind: num | text | bool
    ("Id", "id", "num"), ("NDB_No", "ndb_no", "text"), ("Description", "description", "text"),
    ("Water_g", "water_g", "num"), ("Energy_Kcal", "energy_kcal", "num"), ("Protein_g", "protein_g", "num"),
    ("Lipid_Tot_g", "lipid_tot_g", "num"), ("Ash_g", "ash_g", "num"), ("Carbohydrt_g", "carbohydrt_g", "num"),
    ("Fiber_TD_g", "fiber_td_g", "num"), ("Sugar_Tot_g", "sugar_tot_g", "num"),
    ("Calcium_mg", "calcium_mg", "num"), ("Iron_mg", "iron_mg", "num"), ("Magnesium_mg", "magnesium_mg", "num"),
    ("Phosphorus_mg", "phosphorus_mg", "num"), ("Potassium_mg", "potassium_mg", "num"), ("Sodium_mg", "sodium_mg", "num"),
    ("Zinc_mg", "zinc_mg", "num"), ("Copper_mg", "copper_mg", "num"), ("Manganese_mg", "manganese_mg", "num"),
    ("Selenium_ug", "selenium_ug", "num"),
    ("Vit_C_mg", "vit_c_mg", "num"), ("Thiamin_mg", "thiamin_mg", "num"), ("Riboflavin_mg", "riboflavin_mg", "num"),
    ("Niacin_mg", "niacin_mg", "num"), ("Panto_Acid_mg", "panto_acid_mg", "num"), ("Vit_B6_mg", "vit_b6_mg", "num"),
    ("Folate_Tot_ug", "folate_tot_ug", "num"), ("Folic_Acid_ug", "folic_acid_ug", "num"),
    ("Food_Folate_ug", "food_folate_ug", "num"), ("Folate_DFE_ug", "folate_dfe_ug", "num"),
    ("Choline_Tot_mg", "choline_tot_mg", "num"), ("Vit_B12_ug", "vit_b12_ug", "num"),
    ("Vit_A_IU", "vit_a_iu", "num"), ("Vit_A_RAE", "vit_a_rae", "num"), ("Retinol_ug", "retinol_ug", "num"),
    ("Vit_E_mg", "vit_e_mg", "num"), ("Vit_D_ug", "vit_d_ug", "num"), ("Vit_D_IU", "vit_d_iu", "num"),
    ("Vit_K_ug", "vit_k_ug", "num"),
    ("Alpha_Carot_ug", "alpha_carot_ug", "num"), ("Beta_Carot_ug", "beta_carot_ug", "num"),
    ("Beta_Crypt_ug", "beta_crypt_ug", "num"), ("Lycopene_ug", "lycopene_ug", "num"), ("Lut_Zea_ug", "lut_zea_ug", "num"),
    ("FA_Sat_g", "fa_sat_g", "num"), ("FA_Mono_g", "fa_mono_g", "num"), ("FA_Poly_g", "fa_poly_g", "num"),
    ("Cholestrl_mg", "cholestrl_mg", "num"),
    ("GmWt_1", "gm_wt_1", "num"), ("GmWt_Desc1", "gm_wt_desc1", "text"),
    ("GmWt_2", "gm_wt_2", "num"), ("GmWt_Desc2", "gm_wt_desc2", "text"),
    ("Refuse_Pct", "refuse_pct", "num"), ("IsUSDA", "is_usda", "bool"),
]

SCHEMA = """-- MealPrep Supabase schema. Run FIRST.
create extension if not exists pg_trgm;

create table nutritions (
  id int generated by default as identity primary key,
  ndb_no text, description text not null,
  {nutrition_cols}
);
create index nutritions_description_trgm on nutritions using gin (description gin_trgm_ops);

create table ingredients (
  id int generated by default as identity primary key,
  name text not null,
  unit text not null default '',
  price_per_unit numeric,
  nutrition_id int references nutritions(id) on delete set null
);

create table recipes (
  id int generated by default as identity primary key,
  name text not null, description text,
  servings int not null default 1
);

create table recipe_ingredients (
  id int generated by default as identity primary key,
  recipe_id int not null references recipes(id) on delete cascade,
  ingredient_id int not null references ingredients(id) on delete cascade,
  quantity numeric not null
);

create table meals (
  id int generated by default as identity primary key,
  date date not null,
  meal_type smallint not null default 0,
  title text not null, description text,
  servings int not null default 1,
  recipe_id int references recipes(id) on delete set null
);
create index meals_date_idx on meals(date);

create table meal_ingredients (
  id int generated by default as identity primary key,
  meal_id int not null references meals(id) on delete cascade,
  ingredient_id int not null references ingredients(id) on delete cascade,
  quantity numeric not null
);

create table pantry_items (
  id int generated by default as identity primary key,
  ingredient_id int not null references ingredients(id) on delete cascade,
  quantity numeric not null default 0
);

create table food_log_entries (
  id int generated by default as identity primary key,
  date date not null,
  name text not null,
  calories numeric not null default 0,
  protein_g numeric not null default 0,
  fiber_g numeric, iron_mg numeric,
  is_plant boolean not null default false,
  ingredient_id int references ingredients(id) on delete set null,
  meal_id int references meals(id) on delete set null,
  client_id text not null unique,
  created_at timestamptz not null default now()
);
create index food_log_entries_date_idx on food_log_entries(date);

create table body_measurements (
  id int generated by default as identity primary key,
  date date not null,
  waist_in numeric not null, height_in numeric not null,
  client_id text not null unique
);

create table quick_add_items (
  id int generated by default as identity primary key,
  name text not null,
  calories numeric not null default 0, protein_g numeric not null default 0,
  fiber_g numeric not null default 0, iron_mg numeric not null default 0,
  is_plant boolean not null default false,
  sort_order int not null default 0
);

create table user_preferences (
  id int generated by default as identity primary key,
  key text not null unique,
  value text
);

-- Single-user RLS: only signed-in (authenticated) requests can touch data.
-- The anon key alone grants nothing. Remember to disable public signups
-- in Authentication settings after creating your one user.
{rls}
"""

TABLES_RLS = ["nutritions", "ingredients", "recipes", "recipe_ingredients", "meals",
              "meal_ingredients", "pantry_items", "food_log_entries", "body_measurements",
              "quick_add_items", "user_preferences"]


def q(val, kind):
    if val is None:
        return "null"
    if kind == "num":
        s = str(val).strip()
        if s == "":
            return "null"
        try:
            float(s)
        except ValueError:
            return "null"
        return s
    if kind == "bool":
        return "true" if str(val) in ("1", "True", "true") else "false"
    if kind == "date":
        return "'" + str(val)[:10] + "'"
    if kind == "ts":
        return "'" + str(val).replace("'", "''") + "'"
    return "'" + str(val).replace("'", "''") + "'"


def write(name, content):
    path = os.path.join(OUT, name)
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"  {name}: {len(content)/1024:.0f} KB")


def insert_sql(table, pg_cols, rows):
    if not rows:
        return f"-- {table}: no rows\n"
    lines = [f"insert into {table} ({', '.join(pg_cols)}) values"]
    lines.append(",\n".join("(" + ", ".join(r) + ")" for r in rows) + ";")
    return "\n".join(lines) + "\n"


def main():
    db = sqlite3.connect(DB)
    db.row_factory = sqlite3.Row
    cur = db.cursor()
    counts = {}

    nutrition_col_defs = ",\n  ".join(
        f"{pg} numeric" if kind == "num" else (f"{pg} boolean not null default true" if kind == "bool" else f"{pg} text")
        for _, pg, kind in NUTRITION_COLS if pg not in ("id", "ndb_no", "description"))
    rls = "\n".join(
        f"alter table {t} enable row level security;\n"
        f'create policy "owner_all_{t}" on {t} for all to authenticated using (true) with check (true);'
        for t in TABLES_RLS)
    write("001_schema.sql", SCHEMA.format(nutrition_cols=nutrition_col_defs, rls=rls))

    # nutritions, chunked
    rows = cur.execute("SELECT * FROM Nutritions ORDER BY Id").fetchall()
    counts["nutritions"] = len(rows)
    pg_cols = [pg for _, pg, _ in NUTRITION_COLS]
    chunk_size = 1000
    n_chunks = 0
    for start in range(0, len(rows), chunk_size):
        n_chunks += 1
        chunk = rows[start:start + chunk_size]
        vals = [[q(r[sq], kind) for sq, _, kind in NUTRITION_COLS] for r in chunk]
        write(f"002_nutritions_{n_chunks:02d}.sql", insert_sql("nutritions", pg_cols, vals))

    # core tables
    core = []
    spec = [
        ("Ingredients", "ingredients",
         [("Id", "id", "num"), ("Name", "name", "text"), ("Unit", "unit", "text"),
          ("PricePerUnit", "price_per_unit", "num"), ("NutritionId", "nutrition_id", "num")]),
        ("Recipes", "recipes",
         [("Id", "id", "num"), ("Name", "name", "text"), ("Description", "description", "text"),
          ("Servings", "servings", "num")]),
        ("RecipeIngredients", "recipe_ingredients",
         [("Id", "id", "num"), ("RecipeId", "recipe_id", "num"), ("IngredientId", "ingredient_id", "num"),
          ("Quantity", "quantity", "num")]),
        ("Meals", "meals",
         [("Id", "id", "num"), ("Date", "date", "date"), ("MealType", "meal_type", "num"),
          ("Title", "title", "text"), ("Description", "description", "text"),
          ("Servings", "servings", "num"), ("RecipeId", "recipe_id", "num")]),
        ("MealIngredients", "meal_ingredients",
         [("Id", "id", "num"), ("MealId", "meal_id", "num"), ("IngredientId", "ingredient_id", "num"),
          ("Quantity", "quantity", "num")]),
        ("PantryItems", "pantry_items",
         [("Id", "id", "num"), ("IngredientId", "ingredient_id", "num"), ("Quantity", "quantity", "num")]),
        ("QuickAddItems", "quick_add_items",
         [("Id", "id", "num"), ("Name", "name", "text"), ("Calories", "calories", "num"),
          ("ProteinG", "protein_g", "num"), ("FiberG", "fiber_g", "num"), ("IronMg", "iron_mg", "num"),
          ("IsPlant", "is_plant", "bool"), ("SortOrder", "sort_order", "num")]),
    ]
    for sq_table, pg_table, cols in spec:
        rows = cur.execute(f"SELECT * FROM {sq_table} ORDER BY Id").fetchall()
        counts[pg_table] = len(rows)
        vals = [[q(r[sq], kind) for sq, _, kind in cols] for r in rows]
        core.append(insert_sql(pg_table, [pg for _, pg, _ in cols], vals))
    prefs = cur.execute("SELECT * FROM UserPreferences WHERE Key LIKE 'Log%' ORDER BY Id").fetchall()
    counts["user_preferences"] = len(prefs)
    core.append(insert_sql("user_preferences", ["id", "key", "value"],
                           [[q(r["Id"], "num"), q(r["Key"], "text"), q(r["Value"], "text")] for r in prefs]))
    write("003_core.sql", "\n".join(core))

    # log tables with client_id backfill
    log = []
    rows = cur.execute("SELECT * FROM FoodLogEntries ORDER BY Id").fetchall()
    counts["food_log_entries"] = len(rows)
    vals = []
    for r in rows:
        cid = r["ClientId"] if r["ClientId"] else f"srv-{r['Id']}"
        vals.append([q(r["Id"], "num"), q(r["Date"], "date"), q(r["Name"], "text"),
                     q(r["Calories"], "num"), q(r["ProteinG"], "num"), q(r["FiberG"], "num"), q(r["IronMg"], "num"),
                     q(r["IsPlant"], "bool"), q(r["IngredientId"], "num"), q(r["MealId"], "num"),
                     q(cid, "text"), q(r["CreatedAt"], "ts")])
    log.append(insert_sql("food_log_entries",
                          ["id", "date", "name", "calories", "protein_g", "fiber_g", "iron_mg",
                           "is_plant", "ingredient_id", "meal_id", "client_id", "created_at"], vals))
    rows = cur.execute("SELECT * FROM BodyMeasurements ORDER BY Id").fetchall()
    counts["body_measurements"] = len(rows)
    vals = []
    for r in rows:
        cid = r["ClientId"] if r["ClientId"] else f"srv-{r['Id']}"
        vals.append([q(r["Id"], "num"), q(r["Date"], "date"), q(r["WaistIn"], "num"), q(r["HeightIn"], "num"), q(cid, "text")])
    log.append(insert_sql("body_measurements", ["id", "date", "waist_in", "height_in", "client_id"], vals))
    write("004_log.sql", "\n".join(log))

    # sequences + verification
    finish = ["-- reset identity sequences past imported ids"]
    for t in TABLES_RLS:
        finish.append(f"select setval(pg_get_serial_sequence('{t}', 'id'), coalesce((select max(id) from {t}), 0) + 1, false);")
    finish.append("\n-- verification: compare these counts against the generator's printout")
    finish.append("\nunion all\n".join(f"select '{t}' as tbl, count(*) from {t}" for t in TABLES_RLS) + "\norder by tbl;")
    write("005_finish.sql", "\n".join(finish) + "\n")

    print("\nExpected row counts (compare with 005 output):")
    for t in TABLES_RLS:
        print(f"  {t}: {counts.get(t, 0)}")


if __name__ == "__main__":
    main()
